# Generated by Django 5.1.3 on 2024-12-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='node',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
